<a href="https://colab.research.google.com/github/kdstheace/Project_Financial_Analysis/blob/Daniel/Financial_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame
import matplotlib.pyplot as plt

import tensorflow as tf
import seaborn as sns

from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
#1) 데이터 준비
raw_data = pd.read_csv('drive/MyDrive/Colab Notebooks/data/bankruptcy_data.csv')
X = raw_data.drop('Bankrupt?', axis=1)
y = np.array(raw_data['Bankrupt?'])

print(X.shape)
print(y.shape)
X

(6819, 95)
(6819,)


ROA(C) before interest and depreciation before interest  ...   Equity to Liability
0                                              0.370594         ...              0.016469
1                                              0.464291         ...              0.020794
2                                              0.426071         ...              0.016474
3                                              0.399844         ...              0.023982
4                                              0.465022         ...              0.035490
...                                                 ...         ...                   ...
6814                                           0.493687         ...              0.029890
6815                                           0.475162         ...              0.038284
6816                                           0.472725         ...              0.097649
6817                                           0.506264         ...              0.044009
6818                                           0.493053         ...              0.233902

[6819 rows x 95 columns]

In [ ]:
# encoder = LabelEncoder()
# tmp = encoder.fit_transform(y)
# y_data = pd.get_dummies(tmp).values
# y_data

array([[0, 1],
       [0, 1],
       [0, 1],
       ...,
       [1, 0],
       [1, 0],
       [1, 0]], dtype=uint8)

In [ ]:
scaler = StandardScaler()
scaled_DB = scaler.fit_transform(X)

X = pd.DataFrame(scaled_DB, columns=X.columns)
X


ROA(C) before interest and depreciation before interest  ...   Equity to Liability
0                                             -2.217909         ...             -0.622067
1                                             -0.673828         ...             -0.535573
2                                             -1.303672         ...             -0.621960
3                                             -1.735886         ...             -0.471826
4                                             -0.661778         ...             -0.241715
...                                                 ...         ...                   ...
6814                                          -0.189395         ...             -0.353693
6815                                          -0.494676         ...             -0.185856
6816                                          -0.534845         ...              1.001206
6817                                           0.017875         ...             -0.071364
6818                                          -0.199839         ...              3.725729

[6819 rows x 95 columns]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=5)

print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(5455, 95)
(1364, 95)
(5455,)
(1364,)


In [ ]:
model = Sequential()

model.add(Dense(units=100, activation='relu', input_dim=95))
model.add(Dense(units=50, activation='relu'))
model.add(Dense(units=25, activation='relu'))
model.add(Dense(units=10, activation='relu'))
model.add(Dense(units=1, activation='sigmoid'))

model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_15 (Dense)             (None, 100)               9600      
_________________________________________________________________
dense_16 (Dense)             (None, 50)                5050      
_________________________________________________________________
dense_17 (Dense)             (None, 25)                1275      
_________________________________________________________________
dense_18 (Dense)             (None, 10)                260       
_________________________________________________________________
dense_19 (Dense)             (None, 1)                 11        
Total params: 16,196
Trainable params: 16,196
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.compile(optimizer='Adam', loss='mae', metrics=['accuracy'])
hist = model.fit(X_train, y_train, epochs=100, validation_data=(X_test, y_test), verbose=1)

Epoch 1/100
171/171 [==============================] - 1s 4ms/step - loss: 0.2321 - accuracy: 0.8300 - val_loss: 0.0340 - val_accuracy: 0.9663
Epoch 2/100
171/171 [==============================] - 0s 3ms/step - loss: 0.0317 - accuracy: 0.9685 - val_loss: 0.0338 - val_accuracy: 0.9663
Epoch 3/100
171/171 [==============================] - 0s 2ms/step - loss: 0.0329 - accuracy: 0.9671 - val_loss: 0.0338 - val_accuracy: 0.9663
Epoch 4/100
171/171 [==============================] - 0s 2ms/step - loss: 0.0319 - accuracy: 0.9681 - val_loss: 0.0337 - val_accuracy: 0.9663
Epoch 5/100
171/171 [==============================] - 0s 2ms/step - loss: 0.0320 - accuracy: 0.9680 - val_loss: 0.0337 - val_accuracy: 0.9663
Epoch 6/100
171/171 [==============================] - 0s 2ms/step - loss: 0.0306 - accuracy: 0.9694 - val_loss: 0.0337 - val_accuracy: 0.9663
Epoch 7/100
171/171 [==============================] - 0s 2ms/step - loss: 0.0312 - accuracy: 0.9688 - val_loss: 0.0337 - val_accuracy: 0.9663

In [ ]:
scores = model.evaluate(X_test, y_test)
print(scores[0]*100)
print("\n%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

43/43 [==============================] - 0s 1ms/step - loss: 0.0337 - accuracy: 0.9663
3.37243415415287

accuracy: 96.63%


In [ ]:
print(X.values[0])
pred = model.predict(X.values[3].reshape(1, -1))

np.argmax(pred)

[-2.21790935 -2.04579778 -2.400361   -0.3833337  -0.38263796  0.01645586
 -0.02351613 -0.02016467 -0.08747854 -0.03128096 -0.61633368 -0.75071265
 -0.54525631 -0.1519207  -0.82938817 -1.27924735 -1.27522823 -1.27614661
 -1.7941056  -0.67108117 -0.0256974  -0.47137147 -1.37514996 -0.02529942
  0.0199968  -0.01203116 -0.01226154 -0.0102986  -0.18225906 -0.01372053
 -0.11911848 -0.76929667 -0.01211076 -0.03423674 -0.09252031 -0.02622613
  1.75084501 -1.75084501 -0.13350494  0.95978443  0.04186474 -0.47127476
 -1.4604946  -0.33202719 -0.54034425 -0.04596654 -0.03833275 -0.66172583
 -0.40712275 -0.15518519 -0.01702393 -0.23712348 -0.03822197 -2.39372912
 -1.15583271 -1.52057236 -0.86182012 -0.02093664 -0.07281797  1.12626706
 -0.56375173 -0.04537106 -0.09588652 -0.41289575 -1.24533376  0.56848699
 -0.09497948 -1.2325935  -0.0436103   1.31402695 -0.1754214   1.29975071
 -0.01961903 -0.68539738  0.00394752 -0.01211076 -0.41289575  0.56848699
  0.55842785 -0.2570306  -0.10821821 -1.24723084 -0

0

In [ ]:
print(model.predict(X))
print(y)

[[2.4349749e-19]
 [1.2348894e-19]
 [2.0569787e-13]
 ...
 [8.2957255e-14]
 [7.3331803e-14]
 [5.8340167e-16]]
[1 1 1 ... 0 0 0]
